name: Node.js CI

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Start Postgres
      run: |
        docker run -d --name postgres -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -p 5432:5432 postgres
        sleep 10 # Give Postgres time to initialize

    - name: Install dependencies  
      run: npm install

    - name: Run tests
      env:
        NODE_ENV: test
        DB_HOST: localhost
        DB_PORT: 5432
        DB_USER: postgres
        DB_PASS: postgres
        DB_NAME: testdb  
      run: npm test

    - name: Stop Postgres
      run: docker stop postgres
